CXXFLAGS= -std:c++latest -O2 -W4 -EHsc

test: tests.exe
	./tests.exe

tests.exe: main.obj
	$(CXX) $(CXXFLAGS) $** -link -out:$@

main.obj: main.cpp
	$(CXX) $(CXXFLAGS) -c main.cpp

clean:
	del main.obj tests.exe

.PHONY: clean
